<a href="https://colab.research.google.com/github/Divyanshu-ISM/Oil-and-Gas-data-analysis/blob/master/SinglePhaseFlowSimulator1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Just a Simple Reservoir Simulation for a 1 Phase , Incompressible Flow in 1D**

## - The aim is to clearly understand the workflow.

 ###              --- Divyanshu Vyas (IIT ISM Dhanbad, India)

A single-phase fluid reservoir is described by four equal blocks. The reservoir is horizontal and has homogeneous and
isotropic rock properties, k = 270 md and $\phi$ = 0.27. The gridblock dimensions
are $ \triangle $ x = 300 ft, $\triangle\$ y = 350 ft, and h = 40 ft. The reservoir fluid properties are
B = B ° = 1 RB/STB, density = 50 Ibm/ft 3, and visc = 0.5 cp. The reservoir left
boundary is kept at constant pressure of 4000 psia, and the reservoir right
boundary is sealed off to flow. A 7 in vertical well was drilled at the center of
gridblock 4. The well produces 600 STB/D of fluid and has a skin factor of 1.5.
Assuming that the reservoir rock and fluid are incompressible, find the pressure
distribution in the reservoir and the FBHP of the well. Perform a material balance
check

In [1]:
# 4 Blocks 1D (x-direction) flow. --> 1x4 array. 

k = 270
A = 350*40

u = 0.5
B = 1

rho = 50 #lbm/ft3

l = 300 #delta x


In [5]:
# For block 1 -> Flow equation :
# Tx(p2 - p1) + qbw = 0 
# Tx.p2 - Tx.p1 + 2.Tx.5000 - 2.Tx.p1 = 0 
# Tx.p2 - 3.Tx.p1 + 2.Tx.5000 = 0

Tx = (0.001127*k*A)/(u*B*l)

In [21]:
print(Tx,3*Tx, 2*Tx*4000)

28.4004 85.2012 227203.2


#1. -85.2012 P1  + 28.4004 P2 + 0 P3 + 0 P4 = - 227203.2

In [7]:
#for block 2 -->

# Tx(p1-p2) + Tx(p3-p2) = 0

# Tx.p1 - Tx.p2 + Tx.p3 - Tx.p2 = 0 

# Tx.p1 - 2.Tx.P2 + Tx.P3 + 0. P4


# 2. 28.4004 P1 - 56.8008 P2 + 28.4004 P3 + 0.P4 = 0

In [8]:
#For block 3 -->

# Tx(P2-P3) + Tx(P4 - P3) = 0 

# TxP2 - 2TxP3 + TxP4 = 0

# 3. 0 P1 + 28.4004 P2 - 56.8008 P3 + 28.4004 P4 = 0

In [9]:
#for block 4 --->

# Tx(P3 - P4) + 0 - 600 = 0

#4. 0 P1 + 0 P2 + 28.4004 P3 - 28.4004 P4 = 600

In [11]:
import numpy as np


In [12]:
# SO the Pressure coefficient matrix becomes 

C = np.array( [[-85.2012,28.4004,0,0],
               [28.4004,-56.8008,28.4004,0],
               [0,28.4004,-56.8008,28.4004],
               [0,0,28.4004,-28.4004]])

In [13]:
C

array([[-85.2012,  28.4004,   0.    ,   0.    ],
       [ 28.4004, -56.8008,  28.4004,   0.    ],
       [  0.    ,  28.4004, -56.8008,  28.4004],
       [  0.    ,   0.    ,  28.4004, -28.4004]])

In [22]:
# Now the rhs constants matrix = 

b = np.array([-227203.2,0,0,600]).reshape(4,1)

In [23]:
b

array([[-227203.2],
       [      0. ],
       [      0. ],
       [    600. ]])

In [24]:
C_inv = np.linalg.inv(C)

In [25]:
p = np.dot(C_inv,b)

In [26]:
p

array([[3989.4367685 ],
       [3968.31030549],
       [3947.18384248],
       [3926.05737947]])

In [28]:
#CORRECTOO! These are the pressures of the gridblocks 1,2,3,4 respectively. 